export const WITTY_PHRASES = [
  "Reticulating splines...",
  "Generating witty dialogue...",
  "Swapping time and space...",
  "Spinning the wheel of fortune...",
  "Loading the loading screen...",
  "Calculating the meaning of life...",
  "Pixelating the universe...",
  "Adjusting the flux capacitor...",
  "Calibrating the moral compass...",
  "Counting to infinity... twice...",
  "Defragmenting the coffee machine...",
  "Enchanting the silicon...",
  "Optimizing the boredom levels...",
  "Updating the laws of physics...",
  "Locating the 'Any' key...",
  "Reversing the polarity of the neutron flow...",
  "Downloading more RAM...",
  "Herding digital cats...",
  "Waking up the hamsters...",
  "Polishing the pixels...",
  "Bending the space-time continuum...",
  "Consulting the rubber duck...",
  "Shoveling coal into the server...",
  "Brewing fresh code...",
  "Untangling the internet...",
  "Wait, I thought YOU were loading...",
  "Mining for virtual gold...",
  "Watering the cloud...",
  "Stoking the digital fire...",
  "Synchronizing watches...",
  "Initializing the 'I'm feeling lucky' button...",
  "Searching for the lost city of Atlantis...",
  "Decoding the Matrix...",
  "Inflating the ego...",
  "Defeating the final boss...",
  "Rerolling for better stats...",
  "Buffing the user experience...",
  "Nerfing the bugs...",
  "Charging the lasers...",
  "Sharpening the pencils...",
  "Aligning the planets...",
  "Waiting for the stars to align...",
  "Convincing the CPU to cooperate...",
  "Feeding the trolls...",
  "Sweeping the bit-bucket...",
  "Chasing the cursor...",
  "Collecting the dragon balls...",
  "Opening the pod bay doors...",
  "Searching for Sarah Connor...",
  "Constructing additional pylons...",
  "Zerg rushing the backend...",
  "Doing the Kessel Run in 12 parsecs...",
  "Calculating the ultimate question...",
  "Preparing for warp speed...",
  "Assembling the Avengers...",
  "Sorting the Hogwarts houses...",
  "Consulting the Oracle...",
  "Igniting the lightsabers...",
  "Powering up the warp drive...",
  "Summoning the code spirits...",
  "Translating binary to interpretive dance...",
  "Teaching a robot to love...",
  "Counting pixels for accuracy...",
  "Painting the screen with light...",
  "Sending a carrier pigeon...",
  "Whispering to the motherboard...",
  "Tickling the transistors...",
  "Singing a lullaby to the hard drive...",
  "Knocking on the firewall...",
  "Cleaning the cache (it was dusty)...",
  "Sorting the bit-stream by color...",
  "Encrypted for your protection (maybe)...",
  "Asking the magic 8-ball...",
  "Checking the crystal ball...",
  "Rolling a natural 20...",
  "Avoiding the blue screen of death...",
  "Distracting the garbage collector...",
  "Polishing the chrome...",
  "Oil-changing the engine...",
  "Inflating the buttons...",
  "Checking under the hood...",
  "Tuning the radio to static...",
  "Watching the paint dry...",
  "Watching the grass grow...",
  "Waiting for Godot...",
  "Calculating the air-speed velocity of an unladen swallow...",
  "Checking if the refrigerator light stays on...",
  "Counting the holes in the ceiling...",
  "Thinking of a number between 1 and 10...",
  "Wait, is that a bug or a feature?...",
  "Trying to remember where I left my keys...",
  "Pondering the mysteries of CSS...",
  "Debugging the debugger...",
  "Refactoring the refactor...",
  "Merging the unmergeable...",
  "Resolving the irresolvable...",
  "Pushing to prod on a Friday...",
  "Living on the edge (of the stack)...",
  "Bypassing the main deflector dish...",
  "Modulating the phase variance...",
];

export function getRandomPhrase(): string {
  return WITTY_PHRASES[Math.floor(Math.random() * WITTY_PHRASES.length)];
}
